### ISSUE TITLE
Why NLL is negative during the training？

### ISSUE THREAD

**Issue by IMSEMZPZ** [andreas128/SRFlow#54]
Thanks for your impressive work. During the training process, we found that the output NLL is negative. But theoretically, NLL should be positive. Is there any explanation for this?

**Comment by Boltzmachine** [comment]
Same question. It confuses me a lot

**Comment by martin-danelljan** [comment]
Hi. 

Note that the NLL -log(p) for a **discrete distribution** p is always positive since 0 <= p <= 1.

However, for a **continuous distribution** we instead have a **probability density** p. We have p >=0. The other main constraint is that p should integrate to 1 over the domain. So there is nothing stopping p to be larger than one at a point x. And therefore  -log(p(x))  may be negative.

For more details, please read about probability densities
https://en.wikipedia.org/wiki/Probability_density_function

**Comment by Boltzmachine** [comment]
Oh got it! Thanks so much!
